replicaCount: 1
# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: ccr.civiceye.com/civiceye/demo_image
  sha256: b835a1179d54edd2566299b8dd800e4b5c4fd3ed47bd0e3c8996563915134f11
hostname: "dev.test-civiceye.com"