apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-deployments
spec:
  generators:
    - git:
        repoURL: git@github.com:angelnar11/demo-cicd.git
        revision: HEAD
        directories:
          # here it will read the paths under configs and the subpaths under the config paths
          - path: deployments/*/*
  template:
    metadata:
      namespace: demo
      # you can use the path strings with / delimiter as variables
      name: "demo-{{path.basename}}"
    spec:
      project: default
      sources:
      - repoURL: git@github.com:angelnar11/demo-cicd.git
        path: chart/demo-chart
        targetRevision: HEAD
        helm:
          valueFiles:
          - "$values/deployments/{{path[1]}}/{{path[2]}}/values.yaml"
      - repoURL: git@github.com:angelnar11/demo-cicd.git
        targetRevision: HEAD
        ref: values
      syncPolicy:
        automated:
          prune: true
      destination:
        # specify different destinations
        namespace: default
        server: https://kubernetes.default.svc
      revisionHistoryLimit: 5
      syncPolicy:
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
          allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
        syncOptions:     # Sync options which modifies sync behavior
        - CreateNamespace=true